### ISSUE TITLE
Legion Go with "bazzite"

### ISSUE THREAD

**Issue by Camelot631** [open-goal/decky-plugin#11]
Hello....Thanks for this highlight....But I still have another question.... Steam Deck no problems, works perfectly...

Legion with Win11 is also wonderful... Legion Go with "bazzite"... the DeckyLoader plugin doesn't work (can't find the ISOs, even though they're saved in the right place)... I also can't view the "Jak's" individually in Steam (as described in the doc).. because the directory structure is somehow not found (before the DeckyLoader plugin)...and is not installed like on the Steam Deck.

OpenGOAL as a launcher in Steam works with “bazzite” on the Legion Go.

Maybe this could be taken into account in the future... ;)

Greetings

Rainer B. (Camelot631)

**Comment by xTVaser** [comment]
I'm really confused as to what the problem is?

The most common complaint people talk about in regards to the decky plugin is not being able to make shortcuts, but this is mostly because making steam shortcuts is very much a total hack.

But I'm really just not understanding what you are describing here at all:
> Legion with Win11 is also wonderful... Legion Go with "bazzite"... the DeckyLoader plugin doesn't work (can't find the ISOs, even though they're saved in the right place)... I also can't view the "Jak's" individually in Steam (as described in the doc).. because the directory structure is somehow not found (before the DeckyLoader plugin)...and is not installed like on the Steam Deck.
> OpenGOAL as a launcher in Steam works with “bazzite” on the Legion Go.

**Comment by Camelot631** [comment]
> I'm really confused as to what the problem is?
> 
> The most common complaint people talk about in regards to the decky plugin is not being able to make shortcuts, but this is mostly because making steam shortcuts is very much a total hack.
> 
> But I'm really just not understanding what you are describing here at all:
> 
> > Legion with Win11 is also wonderful... Legion Go with "bazzite"... the DeckyLoader plugin doesn't work (can't find the ISOs, even though they're saved in the right place)... I also can't view the "Jak's" individually in Steam (as described in the doc).. because the directory structure is somehow not found (before the DeckyLoader plugin)...and is not installed like on the Steam Deck.
> > OpenGOAL as a launcher in Steam works with “bazzite” on the Legion Go.
> 
> What is legion, what is legion go, how does bazzite relate to this, how does this relate to Win11, what does a directory structure have to do with seeing the jak games in steam, etc 😕



Hello.

So...if I install the "Jak's" on the Steam Deck via the DeckyLoader.Plugin, it works wonderfully, I can then also add the link as a third-party game in Steam...

Legion Go is a handheld from Lenovo... :)

https://www.lenovo.com/us/en/p/handheld/legion-go/len106g0001?selectModel=83E1001YUS

When I do the same thing on the Lenovo Legieon Go with "bazzite" (bazzite is a LinuxDist that is basically built the same as the SteamOS for Steam Deck), it doesn't work the same as on the Steam Deck because the plugin & the OpenGOAL -Launcher "supposedly" doesn't find the folders...

**Comment by xTVaser** [comment]
Yeah I wouldn't really expect the decky plugin to work on something other than the steamdeck, the underlying tools and assumptions assume its a steamdeck / steamos.

As for the fully fledged Launcher not working, that also doesn't really work properly on the steamdeck, at best it is clunky and is the reason the decky plugin was made.

Your remaining option is to install it manually as someone would do on a normal linux platform without the assistance of the launcher/plugin https://opengoal.dev/docs/usage/installation/#linux-1 (this documentation is out of date in terms of installing and playing jak 2, will update it soon)

I can't imagine why the fully fledged launcher is having problems finding folders, since basically all folders paths are provided by the user, but I don't have that device so it isn't something I can realistically debug or support anyway.  For that reason I'm going to close out the issue, someone with the hardware will have to contribute patches or documentation for how to use it.
